<?php
/**
 * @file
 * Provides a Views plugin for displaying filter buttons for an Isotope magical layout.
 */

/**
 * Implements hook_views_api().
 */
function isotope_filter_views_views_api() {
  return array('api' => 3);
}

/**
 * Preprocess function for theme hook views_view_isotope_filter (implemented as views_view_isotope_filter.tpl.php).
 */
function template_preprocess_views_view_isotope_filter(&$vars) {
  // Run preprocess function for unformatted style
  template_preprocess_views_view_unformatted($vars);

  // clean taxonomy terms to be usable for filters
  $rows = $vars['rows'];
  $filter_array = array();

  foreach ($rows as $id => $row) {
    $row = trim($row);
    $filter = drupal_clean_css_identifier(strtolower($row));
    $vars['rows'][$id] = $row;
    $filter_array[$id] = $filter;
  }

  // get options and add unique id for button group
  $view =  $vars['view'];
  $options = $vars['options'];

  $button_group_id = 'filter-buttons-' . $view->vid . '-' . drupal_clean_css_identifier($view->current_display);
  $vars['button_group_id'] = $button_group_id;
  $vars['title'] = $options['isotope_filter_title'];
  $vars['reset_label'] = ($options['isotope_filter_reset_label'] === '<none>') ? '' : $options['isotope_filter_reset_label'];
  $vars['filter_array'] = $filter_array;

  isotope_filter_apply($button_group_id, $options);
}

